import { useEffect, useRef } from 'react';
import { officialFormat } from '../data/bec';
import ReadingText from './ReadingText';
import { stages } from '../types';
import type { ExposurePack, ExposurePhrase, ExposureSession, LearningState, SavedPhrase, Stage } from '../types';
import LearningStates from './LearningStates';
interface Props { pack: ExposurePack; session: ExposureSession; phrases: SavedPhrase[]; rescue: boolean; onChange: (patch: Partial<ExposureSession>) => void; onSave: (phrase: ExposurePhrase, state?: LearningState) => void; onFinish: () => void; onLegacy: () => void }
export default function Exposure({ pack, session: s, phrases, rescue, onChange, onSave, onFinish, onLegacy }: Props) {
  const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { heading.current?.focus(); }, [s.stage]);
  function go(stage: Stage) { onChange({ stage, visited: [...new Set([...s.visited, stage])] }); window.scrollTo(0,0); }
  const index = stages.indexOf(s.stage);
  return <div className="exercise-page exposure-page">
    <div className="section-top"><button className="text-button" onClick={onFinish}>Finish for today</button><span className="muted">{pack.topic ?? 'Challenge / Timeline'}</span></div>
    <nav className="stage-nav" aria-label="Learning stages">{stages.map((stage,i) => <button key={stage} aria-current={s.stage === stage ? 'step' : undefined} onClick={() => go(stage)}><span>{String(i+1).padStart(2,'0')}</span>{stage}{i > 3 && <small>Optional</small>}</button>)}</nav>
    <p className="eyebrow">{index < 3 ? 'READ. COMPARE. LET IT SETTLE.' : 'BORROW THE PATTERN. MAKE IT YOURS.'}</p><h1 className="exercise-title" ref={heading} tabIndex={-1}>{s.stage} <span className="muted">/ {['Meet the language', 'Look a little closer', 'Find the right fit', 'Imitate & transform', 'Gradual recall', 'Independent output'][index]}</span></h1>
    {s.stage === 'Absorb' && <><p className="intro">{pack.intent} Read at your own pace. There is nothing to write yet.</p>{pack.reading && <ReadingText pack={pack}/>}<h2 className="section-title">Expressions in context</h2><div className="exposure-cards">{pack.phrases.map((p,i) => { const saved = phrases.find(item => item.phrase === p.phrase); return <article className="exposure-card" key={p.phrase}><div className="section-top"><span className="small-label">Expression 0{i+1}</span><span className="tag">{p.tone}</span></div><blockquote>{p.phrase}</blockquote><p>{p.context}</p><div className="pattern"><span className="small-label">Reusable pattern</span><p>{p.pattern}</p></div><p className="muted">{p.explanation}</p><details><summary>See it in another business context</summary><p>{p.example}</p>{p.examples.map(example => <p key={example}>{example}</p>)}</details>{rescue && <details><summary>中文辅助</summary><p lang="zh-CN">{p.zh}</p></details>}<button className="secondary" disabled={!!saved} onClick={() => onSave(p)}>{saved ? 'Saved to Phrase Bank' : 'Save phrase'}</button><LearningStates value={saved?.learningState} onChange={state => onSave(p,state)}/></article>; })}</div></>}
    {s.stage === 'Notice' && <><p className="intro">Compare the intent, the tone, and the next step. Think about each question, then open the observation.</p><div className="pattern-comparison">{pack.phrases.map(p => <p key={p.pattern}>{p.pattern}</p>)}</div>{pack.notices.map(n => <details className="notice-question" key={n.question}><summary>{n.question}</summary><p>{n.answer}</p></details>)}<p className="quiet">Reading and noticing are enough for a useful session. You can finish here.</p></>}
    {s.stage === 'Choose' && <><p className="prompt">{pack.choice.context}</p><fieldset className="options"><legend className="sr-only">Choose the best interpretation</legend>{pack.choice.options.map((o,i) => <label className={`option ${s.choice === i ? 'selected' : ''}`} key={o.text}><input type="radio" name="exposure-choice" checked={s.choice === i} onChange={() => onChange({ choice: i, checked: false })}/><span>{o.text}</span></label>)}</fieldset><button className="primary reveal" disabled={s.choice === null} onClick={() => onChange({ checked: true })}>Explore the choices</button>{s.checked && <div className="answer" role="status"><p className="eyebrow">{s.choice === pack.choice.preferred ? 'A GOOD FIT FOR THIS INTENT' : 'COMPARE THE BUSINESS INTENT'}</p>{pack.choice.options.map((o,i) => <div key={o.text} className="option-feedback"><strong>{i+1}{i === s.choice ? ' · Your choice' : ''}{i === pack.choice.preferred ? ' · Best fit here' : ''}</strong><p>{o.explanation}</p></div>)}</div>}</>}
    {s.stage === 'Imitate' && <><p className="intro">Keep the model in view. Borrowing the structure is the point; different wording is welcome.</p>{pack.imitations.map((task,i) => <section className="imitation-task" key={task.label}><h2>{task.label}</h2><blockquote className="model-sentence">{pack.phrases[i]?.phrase}</blockquote><p>{task.context}</p><p className="pattern">{task.scaffold}</p><label htmlFor={`imitate-${i}`}>Your version · {i+1}</label><textarea id={`imitate-${i}`} rows={3} maxLength={3000} value={s.imitation[i]} onChange={e => onChange({ imitation: s.imitation.map((v,j) => j === i ? e.target.value : v) })} placeholder="Use the pattern above, with your own details."/><details><summary>Show a possible version</summary><p>{task.example}</p><p className="muted">Compare the intent and the reason, rather than matching every word.</p></details></section>)}</>}
    {s.stage === 'Recall' && <><p className="intro">Try this when the pattern feels familiar. Reduce the support only when you want to.</p><p className="prompt">{pack.recallContext}</p><label htmlFor="recall-support">Support level</label><select id="recall-support" value={s.hintLevel} onChange={e => onChange({ hintLevel: Number(e.target.value) })}>{['Full example', 'Key phrases', 'Sentence opening', 'Communication intent', 'Scenario only'].map((label,i) => <option key={label} value={i}>{label}</option>)}</select>{s.hintLevel < 4 && <p className="pattern">{[pack.recallModel, ...(pack.recallHints ?? ['revisit · rollout date · in light of · staff training', 'Could we revisit…', 'Invite a review and explain the dependency.'])][s.hintLevel]}</p>}<label htmlFor="recall-response">Your recall attempt</label><textarea id="recall-response" rows={4} maxLength={3000} value={s.recall} onChange={e => onChange({ recall: e.target.value })}/><div className="support-actions"><button className="secondary" onClick={() => onChange({ hintLevel: 0 })}>Show an example</button><button className="text-button" onClick={() => go('Imitate')}>Return to imitation</button></div><fieldset className="recall-feeling"><legend>Optional reflection · no time limit</legend>{(['Hesitated','Comfortable'] as const).map(feeling => <button className="secondary" key={feeling} aria-pressed={s.recallFeeling === feeling} onClick={() => onChange({ recallFeeling: feeling })}>{feeling}</button>)}</fieldset></>}
    {s.stage === 'Produce' && <><p className="intro">An optional space to put it together. Taking time and using support are both welcome.</p><p className="prompt">{pack.produceContext}</p><label htmlFor="produce-response">Your response</label><textarea id="produce-response" rows={6} maxLength={3000} value={s.produce} onChange={e => onChange({ produce: e.target.value })}/><details><summary>Show an example</summary><p>{pack.produceModel}</p></details><details><summary>Give me a hint</summary><p>{pack.produceHint ?? 'Acknowledge the request → explain the constraint → propose a joint review.'}</p></details><div className="support-actions"><button className="secondary" onClick={() => go('Notice')}>Review the patterns</button><button className="secondary" onClick={() => go('Imitate')}>Return to imitation</button></div><p className="quiet">Self-check: {pack.selfCheck ?? 'Did you name the constraint, keep the tone collaborative, and offer a useful next step?'}</p><button className="text-button" onClick={onLegacy}>Open the original output drills</button></>}
    {pack.reading && s.stage !== 'Absorb' && <details className="return-reading"><summary>Revisit the full text</summary><ReadingText pack={pack}/></details>}<div className="pack-bottom">{index < stages.length-1 && <button className="primary" onClick={() => go(stages[index+1])}>{index === 3 ? 'Optional: try Recall' : `Continue to ${stages[index+1]}`} →</button>}<button className="secondary" onClick={onFinish}>Finish for today</button></div><p className="fine-print">Original learning material · {pack.skill ?? 'Business communication'}. Foundation practice, not an official question or mock score. <a href={officialFormat} target="_blank" rel="noreferrer">Official BEC Higher skill requirements ↗</a></p>
  </div>;
}
