import { useState } from 'react';
import type { SavedPhrase } from '../types';
import { markPhrase } from '../lib/exposure';
import Icon from './Icon';
import LearningStates from './LearningStates';
export default function PhraseBank({ phrases, onChange }: { phrases: SavedPhrase[]; onChange: (phrases: SavedPhrase[]) => void }) {
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('All categories');
  const [state, setState] = useState('All states'); const [topic, setTopic] = useState('All topics'); const [adding, setAdding] = useState(false);
  const [draft, setDraft] = useState({ phrase: '', category: '', context: '', tone: '', pattern: '', example: '' });
  const [message, setMessage] = useState('');
  const filtered = phrases.filter(p => (topic === 'All topics' || p.topic === topic) && (category === 'All categories' || p.category === category) && (state === 'All states' || (p.learningState ?? 'Unmarked') === state) && `${p.phrase} ${p.example} ${p.examples?.join(' ') ?? ''} ${p.note} ${p.category} ${p.context ?? ''} ${p.pattern ?? ''} ${p.tone ?? ''} ${p.topic ?? ''} ${p.sourceTitle ?? ''}`.toLowerCase().includes(search.toLowerCase()));
  function addPhrase(e: React.FormEvent) {
    e.preventDefault();
    if (!draft.phrase.trim()) return;
    if (phrases.some(p => p.phrase.toLowerCase() === draft.phrase.trim().toLowerCase())) { setMessage('This expression is already in your bank.'); return; }
    const fields = Object.fromEntries(Object.entries(draft).map(([k,v]) => [k,v.trim()])) as typeof draft;
    onChange([...phrases, { ...fields, category: fields.category || 'Personal', id: crypto.randomUUID(), note: '', savedAt: new Date().toISOString() }]);
    setDraft({ phrase: '', category: '', context: '', tone: '', pattern: '', example: '' }); setAdding(false); setMessage('Your expression has been added.');
    setSearch(''); setCategory('All categories'); setState('All states'); setTopic('All topics');
  }
  return <><p className="eyebrow">LANGUAGE YOU CAN REACH FOR</p><h1>Phrase Bank</h1><p className="intro">Connect expressions with the situations where they help.</p><button className="secondary" aria-expanded={adding} onClick={() => setAdding(!adding)}>{adding ? 'Close phrase form' : 'Add your own expression'}</button>
    {adding && <form className="personal-phrase-form exposure-card" onSubmit={addPhrase}><h2>From your working world</h2><p className="muted">Only the expression is required. No translation needed.</p>{([['phrase','Expression'],['category','Communication function'],['context','Applicable context'],['tone','Tone / register'],['pattern','Reusable pattern'],['example','Transferable example']] as const).map(([key,label]) => <label key={key}>{label}{key !== 'phrase' && ' (optional)'}<textarea rows={2} required={key === 'phrase'} maxLength={key === 'phrase' ? 3000 : 1500} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })}/></label>)}<button className="primary" type="submit">Save personal expression</button></form>}
    {message && <p role="status">{message}</p>}
    <div className="filters phrase-filters"><label><span className="sr-only">Search phrases</span><input type="search" placeholder="Search phrases, context, patterns…" value={search} onChange={e => setSearch(e.target.value)}/></label><label><span className="sr-only">Filter by category</span><select value={category} onChange={e => setCategory(e.target.value)}><option>All categories</option>{[...new Set(phrases.map(p => p.category))].sort().map(c => <option key={c}>{c}</option>)}</select></label><label><span className="sr-only">Filter by learning state</span><select value={state} onChange={e => setState(e.target.value)}>{['All states','Unmarked','Familiar','Almost Mine','Mine'].map(value => <option key={value}>{value}</option>)}</select></label><label><span className="sr-only">Filter by business topic</span><select value={topic} onChange={e => setTopic(e.target.value)}><option>All topics</option>{[...new Set(phrases.map(p => p.topic).filter(Boolean))].map(t => <option key={t}>{t}</option>)}</select></label></div>
    {filtered.length === 0 ? <div className="empty"><Icon name="phrases" size={32}/><h2>{phrases.length ? 'No matching phrases' : 'Make the language yours.'}</h2><p>{phrases.length ? 'Try a different search or filter.' : 'Save a phrase from a pack or add an expression you have encountered at work.'}</p></div>
      : <div className="phrase-list">{filtered.map(p => <article className="saved-phrase" key={p.id}><div className="section-top"><span className="tag">{p.category}</span><span className="muted saved-date">Saved {new Date(p.savedAt).toLocaleDateString('en', { month: 'short', day: 'numeric', year: 'numeric' })}</span></div><h2>{p.phrase}</h2>{p.sourceTitle && <p className="phrase-source">From: {p.sourceTitle}{p.topic ? ` · ${p.topic}` : ''}</p>}{p.context && <p>{p.context}</p>}{p.tone && <p className="muted">{p.tone}</p>}{p.pattern && <p className="pattern">{p.pattern}</p>}<p className="phrase-example">{p.example}</p>{p.examples?.map(example => <p className="phrase-example" key={example}>{example}</p>)}{p.tags && <p className="fine-print">{p.tags.join(' · ')}</p>}<LearningStates value={p.learningState} onChange={state => onChange(phrases.map(item => item.id === p.id ? markPhrase(item,state) : item))}/><p className="fine-print">{p.learningState ? `${p.learningState} · Last practiced: ${new Date(p.lastPracticed ?? p.savedAt).toLocaleDateString('en')} · Next review: ${p.due ?? 'Ready now'}` : 'Unmarked · saving an expression does not mark it as mastered.'}</p><label className="note-label" htmlFor={`note-${p.id}`}>Personal note</label><textarea id={`note-${p.id}`} rows={2} maxLength={1500} placeholder="Where could you use this?" value={p.note} onChange={e => onChange(phrases.map(item => item.id === p.id ? { ...item, note: e.target.value } : item))}/><button className="text-button remove" onClick={() => onChange(phrases.filter(item => item.id !== p.id))}>Remove phrase</button></article>)}</div>}
  </>;
}
