// Isolated browser acceptance: never uses the user's browser profile or learning data.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { expect } = require((process.env.PLAYWRIGHT_MODULE || 'playwright') + '/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.DRILL_TEST_URL || 'http://localhost:4173';
const key = 'business-english-drill:v1';
(async () => {
  fs.mkdirSync('test-results', { recursive: true });
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'Asia/Shanghai' });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const state = () => page.evaluate(k => JSON.parse(localStorage.getItem(k)),key);
  const nav = name => page.getByRole('navigation', {name:'Main navigation'}).getByRole('button',{name,exact:true}).click();
  const stage = name => page.getByRole('navigation',{name:'Learning stages'}).getByRole('button',{name:new RegExp(name)}).click();
  const resume = () => page.getByRole('button',{name:'Open Make room for a realistic timeline.'}).click();
  const noOverflow = async label => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), label + ' horizontal overflow');
  try {
    await page.goto(base); await page.waitForLoadState('networkidle');
    await page.getByRole('button',{name:'Open Make room for a realistic timeline.'}).click();
    await expect(page.locator('.exposure-card')).toHaveCount(4);
    assert.equal(await page.locator('textarea').count(),0);
    assert.equal((await state()).phrases.length,0);
    await expect(page.locator('[lang="zh-CN"]').first()).not.toBeVisible();
    await page.locator('.exposure-card').first().getByText('中文辅助',{exact:true}).click();
    await expect(page.locator('[lang="zh-CN"]').first()).toBeVisible();
    await page.locator('.exposure-card').first().getByRole('button',{name:'Save phrase',exact:true}).click();
    assert.equal((await state()).phrases[0].learningState,undefined);
    await page.locator('.exposure-card').first().getByRole('button',{name:'Almost Mine I can use it with support',exact:true}).click();
    assert.equal((await state()).phrases.length,1);
    assert.equal((await state()).phrases[0].learningState,'Almost Mine');
    await page.screenshot({path:'test-results/exposure-absorb-mobile.png',fullPage:true});
    await page.getByRole('button',{name:'Continue to Notice'}).click();
    await page.locator('.notice-question summary').first().click();
    await expect(page.locator('.notice-question').first()).toContainText('soften the claim');
    await page.getByRole('button',{name:'Finish for today',exact:true}).first().click();
    await expect(page.getByRole('heading',{name:'A little more familiar.'})).toBeVisible();
    let data = await state();
    assert.deepEqual(data.exposureHistory[0].stages,['Absorb','Notice']);
    assert.equal(data.attempts.length,0); assert.equal(data.completedDates.length,0);
    await page.reload(); await resume();
    await expect(page.getByRole('heading',{name:'Notice / Look a little closer'})).toBeVisible();
    await page.getByRole('button',{name:'Continue to Choose'}).click();
    await expect(page.getByRole('button',{name:'Explore the choices'})).toBeDisabled();
    await page.getByRole('radio').nth(3).check();
    await page.getByRole('button',{name:'Explore the choices'}).click();
    await expect(page.locator('.option-feedback')).toHaveCount(4);
    await page.reload(); await resume();
    await expect(page.getByRole('radio').nth(3)).toBeChecked();
    await expect(page.locator('.option-feedback')).toHaveCount(4);
    await stage('Imitate');
    await page.getByLabel('Your version · 1',{exact:true}).fill('Could we revisit the data transfer approach in light of the file format limitations?');
    await page.getByText('Show a possible version',{exact:true}).first().click();
    await expect(page.locator('.imitation-task').first()).toContainText('system’s file format limitations');
    await page.reload(); await resume();
    await expect(page.getByLabel('Your version · 1',{exact:true})).toHaveValue(/data transfer approach/);
    await stage('Recall');
    await page.getByLabel('Support level').selectOption('4');
    await expect(page.locator('.pattern')).toHaveCount(0);
    await page.getByRole('button',{name:'Show an example'}).click();
    await expect(page.locator('.pattern')).toContainText('staff training');
    await page.getByLabel('Your recall attempt').fill('Could we revisit the rollout date?');
    await page.getByRole('button',{name:'Hesitated',exact:true}).click();
    await stage('Produce');
    await page.getByLabel('Your response',{exact:true}).fill('Could we review the remaining dependencies before confirming an earlier date?');
    await page.getByText('Show an example',{exact:true}).click();
    await expect(page.locator('details').first()).toContainText('QC activities');
    await page.getByRole('button',{name:'Return to imitation',exact:true}).click();
    await expect(page.getByLabel('Your version · 1',{exact:true})).toHaveValue(/data transfer approach/);
    await stage('Produce');
    await page.getByRole('button',{name:'Finish for today',exact:true}).first().click();
    data = await state(); assert.equal(data.exposureHistory.length,1); assert.equal(data.exposureHistory[0].stages.length,6);
    assert.equal(data.exposureSession.recallFeeling,'Hesitated');
    await page.getByRole('button',{name:'Back to today',exact:true}).click();
    await nav('Phrase Bank');
    await page.getByLabel('Filter by learning state').selectOption('Almost Mine');
    await expect(page.locator('.saved-phrase')).toHaveCount(1);
    await page.getByRole('searchbox').fill('current budget');
    await expect(page.locator('.saved-phrase')).toHaveCount(1);
    await page.getByRole('button',{name:'Add your own expression'}).click();
    await page.getByLabel('Expression',{exact:true}).fill('What would need to change for this to work?');
    await page.getByLabel('Communication function (optional)').fill('Proposing Alternatives');
    await page.getByRole('button',{name:'Save personal expression'}).click();
    await expect(page.locator('.saved-phrase')).toHaveCount(2);
    assert.equal((await state()).phrases[1].learningState,undefined);
    await page.reload(); await nav('Phrase Bank');
    await expect(page.locator('.saved-phrase')).toHaveCount(2);
    console.log('PASS: input-only completion, six stages, assistance, drafts, reflection, phrase metadata and personal expressions');
    // Advance only the fixture's due date, then reopen the app as on the next visit.
    await page.evaluate(k => { const d=JSON.parse(localStorage.getItem(k)); d.phrases[0].due='2020-01-01'; localStorage.setItem(k,JSON.stringify(d)); },key);
    await page.reload();
    await page.getByRole('button',{name:/1 expressions to revisit/}).click();
    await expect(page.locator('.phrase-review article')).toHaveCount(1);
    await expect(page.locator('.phrase-review article')).toContainText('staffing level');
    await page.locator('.phrase-review').getByRole('button',{name:'Mine I can use it naturally',exact:true}).click();
    await expect(page.locator('.phrase-review article')).toHaveCount(0);
    assert.equal((await state()).phrases[0].learningState,'Mine');
    await nav('Progress'); await expect(page.locator('.exposure-history')).toHaveCount(1);
    await nav('Settings'); await page.getByRole('combobox',{name:'Appearance',exact:true}).selectOption('dark');
    await nav('Today'); await resume(); await stage('Absorb');
    await page.screenshot({path:'test-results/exposure-dark-mobile.png',fullPage:true});
    for (const width of [320,390,1280]) {
      await page.setViewportSize({width,height:900});
      for (const name of ['Absorb','Notice','Choose','Imitate','Recall','Produce']) { await stage(name); await noOverflow(name+' '+width); }
    }
    await stage('Absorb'); await page.screenshot({path:'test-results/exposure-desktop.png',fullPage:true});
    await page.setViewportSize({width:320,height:720});
    await page.addStyleTag({content:'html { font-size: 200%; }'});
    for (const name of ['Absorb','Notice','Choose','Imitate','Recall','Produce']) { await stage(name); await noOverflow(name+' large text'); }
    await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
    await page.reload(); await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
    await context.setOffline(true); await page.reload(); await resume(); await stage('Produce');
    await expect(page.getByLabel('Your response',{exact:true})).toHaveValue(/remaining dependencies/);
    await page.getByLabel('Your response',{exact:true}).fill('A draft written offline.');
    await page.reload(); await resume(); await expect(page.getByLabel('Your response',{exact:true})).toHaveValue('A draft written offline.');
    assert.deepEqual(errors,[]);
    console.log('PASS: scheduled phrase return, transfer example, review rescheduling, progress, dark mode, 320/390/1280 layouts, 200% text and offline draft persistence');
  } catch(error) { await page.screenshot({path:'test-results/exposure-failure.png',fullPage:true}); console.error(await page.locator('main').ariaSnapshot()); throw error; }
  finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
